### ISSUE TITLE
testVideoHRef fails under ffmpeg > 2.5.x

### ISSUE THREAD

**Issue by uzadow** [libavg/libavg#621]
From @klemmster:
```
======================================================================
FAIL: testVideoHRef (AVTest.AVTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/richy/Projects/Libavg/libavg/src/test/AVTest.py", line 239, in testVideoHRef
    testVideoBroken()
  File "/home/richy/Projects/Libavg/libavg/src/test/AVTest.py", line 233, in testVideoBroken
    self.assertRaises(avg.Exception, node.play)
AssertionError: Exception not raised
```

**Comment by uzadow** [comment]
@klemmster: I just tried to figure out (from the original report) which plattform this bug appeard on and failed. Could you post the specs so we can reproduce?

**Comment by klemmster** [comment]
OS: Archinux, The Specs:
```
richy@flux: ~/Projects/libavg/libavg master!
 $ lspci                                                                                                                                                                                    [18:20:37]
00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 (rev 04)
00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 (rev b5)
00:1c.1 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 2 (rev b5)
00:1c.3 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 4 (rev b5)
00:1d.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation QS67 Express Chipset Family LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 6 Series/C200 Series Chipset Family 6 port SATA AHCI Controller (rev 05)
00:1f.3 SMBus: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller (rev 05)
02:00.0 Network controller: Qualcomm Atheros AR9485 Wireless Network Adapter (rev 01)
03:00.0 USB controller: Fresco Logic FL1009 USB 3.0 Host Controller (rev 02)
 
richy@flux: ~/Projects/libavg/libavg master!
 $ sudo pacman -Qs intel                                                                                                                                                                    [18:20:41]
local/intel-gpu-tools 1.10-2
    Tools for development and testing of the Intel DRM driver
local/intel-tbb 4.3_20150209-1
    High level abstract threading library
local/intel-ucode 20150121-1
    Microcode update files for Intel CPUs
local/lib32-mesa 10.5.2-1
    an open-source implementation of the OpenGL specification (32-bit)
local/libva-intel-driver 1.5.1-1
    VA-API implementation for Intel G45 and HD Graphics family
local/linux-ck-sandybridge 3.19.3-2 (ck-sandybridge)
    Linux Kernel and modules with the ck1 patchset featuring the Brain Fuck Scheduler v0.461. Second Gen Intel Core i3/i5/i7 optimized.
local/mesa 10.5.2-1
    an open-source implementation of the OpenGL specification
local/virtualbox-ck-host-modules-sandybridge 4.3.26-3 (ck-sandybridge)
    Host kernel modules for VirtualBox running under Linux-ck. Second Gen Intel Core i3/i5/i7 optimized.
local/xf86-video-intel 2.99.917-4 (xorg-drivers xorg)
    X.org Intel i810/i830/i915/945G/G965+ video drivers

 
richy@flux: ~/Projects/libavg/libavg master!
 $ sudo pacman -Qs ffmpeg                                                                                                                                                                   [18:20:50]
local/ffmpeg 1:2.6.1-2
    Complete and free Internet live audio and video broadcasting solution
local/ffmpeg-compat 1:0.10.15-2
    Complete and free Internet live audio and video broadcasting solution
local/gst-libav 1.4.5-1
    Gstreamer libav Plugin
local/gstreamer0.10-ffmpeg 0.10.13-2 (gstreamer0.10-plugins)
    Gstreamer FFMpeg Plugin
 
richy@flux: ~/Projects/libavg/libavg master!
 $ sudo pacman -Qs boost                                                                                                                                                                    [18:20:59]
local/boost 1.57.0-4
    Free peer-reviewed portable C++ source libraries - development headers
local/boost-libs 1.57.0-4
    Free peer-reviewed portable C++ source libraries - runtime libraries

richy@flux: ~/Projects/libavg/libavg master!
 $ cat /proc/cpuinfo                                                                                                                                                                        [18:21:20]
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz
stepping        : 7
microcode       : 0x29
cpu MHz         : 2399.988
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid xsaveopt
bugs            :
bogomips        : 3392.05
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
……

richy@flux: ~/Projects/libavg/libavg master!
 $ uname -a                                                                                                                                                                                 [18:21:38]
Linux flux 3.19.3-2-ck #1 SMP PREEMPT Wed Apr 8 16:28:22 EDT 2015 x86_64 GNU/Linux
 
richy@flux: ~/Projects/libavg/libavg master!
 $ sudo pacman -Qs mesa                                                                                                                                                                     [18:22:32]
local/glu 9.0.0-3
    Mesa OpenGL Utility library
local/lib32-libtxc_dxtn 1.0.1-5
    S3 Texture Compression (S3TC) library for Mesa (32-bit)
local/lib32-mesa 10.5.2-1
    an open-source implementation of the OpenGL specification (32-bit)
local/lib32-mesa-libgl 10.5.2-1
    Mesa 3-D graphics library (32-bit)
local/libtxc_dxtn 1.0.1-6
    S3 Texture Compression (S3TC) library for Mesa
local/libva-mesa-driver 10.5.2-1
    VA-API implementation for gallium
local/mesa 10.5.2-1
    an open-source implementation of the OpenGL specification
local/mesa-libgl 10.5.2-1
    Mesa 3-D graphics library
```

The error is still present in latest master.

**Comment by uzadow** [comment]
Fails with ffmpeg 2.5.2 under windows as well. I've updated the title.

**Comment by uzadow** [comment]
Fixed under windows with 9629a789565c0e559226591168c3f77b31f73728.
The issue was that ffmpeg now interprets image files as one-frame videos ;-).
@klemmster, if you could verify that it's gone under arch as well, that would be great.

**Comment by klemmster** [comment]
@uzadow Works well!
And tests seem to have speed up quite a bit in the last time.

**Comment by uzadow** [comment]
:-)
