### ISSUE TITLE
Test failed on Raspberry 2

### ISSUE THREAD

**Issue by sissou92** [libavg/libavg#627]
# Configuration:

$ uname -a
Linux raspberrypi 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l GNU/Linux
# Libavg version:

1.8.1
# Test Traces:
## FAIL: testCurve (VectorTest.VectorTestCase)

Traceback (most recent call last):
  File "/home/pi/rpi2-install/xibo/libavg/src/test/VectorTest.py", line 295, in testCurve
    lambda: self.compareImage("testCurve4"),
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 142, in start
    player.play()
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 276, in __nextAction
    action()
  File "/home/pi/rpi2-install/xibo/libavg/src/test/VectorTest.py", line 289, in <lambda>
    (lambda: self.compareImage("testCurve1"),
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 153, in compareImage
    self.compareBitmapToFile(bmp, fileName)
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 180, in compareBitmapToFile
    self.fail(msg)
AssertionError:   testCurve1: Difference image has avg=0.19, std dev=6.88
# 
## FAIL: testTexturedCurve (VectorTest.VectorTestCase)

Traceback (most recent call last):
  File "/home/pi/rpi2-install/xibo/libavg/src/test/VectorTest.py", line 314, in testTexturedCurve
    lambda: self.compareImage("testTexturedCurve2")
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 142, in start
    player.play()
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 276, in __nextAction
    action()
  File "/home/pi/rpi2-install/xibo/libavg/src/test/VectorTest.py", line 312, in <lambda>
    (lambda: self.compareImage("testTexturedCurve1"),
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 153, in compareImage
    self.compareBitmapToFile(bmp, fileName)
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 180, in compareBitmapToFile
    self.fail(msg)
AssertionError:   testTexturedCurve1: Difference image has avg=0.45, std dev=6.49
# 
## FAIL: testMesh (VectorTest.VectorTestCase)

Traceback (most recent call last):
  File "/home/pi/rpi2-install/xibo/libavg/src/test/VectorTest.py", line 681, in testMesh
    lambda: self.compareImage("testMesh8")
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 142, in start
    player.play()
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 276, in __nextAction
    action()
  File "/home/pi/rpi2-install/xibo/libavg/src/test/VectorTest.py", line 673, in <lambda>
    lambda: self.compareImage("testMesh4"),
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 153, in compareImage
    self.compareBitmapToFile(bmp, fileName)
  File "/home/pi/rpi2-install/xibo/libavg/src/test/testcase.py", line 180, in compareBitmapToFile
    self.fail(msg)
AssertionError:   testMesh4: Difference image has avg=0.31, std dev=6.98

---

Ran 275 tests in 98.042s

FAILED (failures=3)
Skipped 12 tests:
  testCanvasMultisampling (OffscreenTest.OffscreenTestCase): Offscreen multisampling not supported
  testBlendMode (ImageTest.ImageTestCase): Blend modes min and max not supported.
  testBlurFX (FXTest.FXTestCase): Not supported if ShaderUsage == MINIMAL
  testHueSatFX (FXTest.FXTestCase): Not supported if ShaderUsage == MINIMAL
  testInvertFX (FXTest.FXTestCase): Not supported if ShaderUsage == MINIMAL
  testShadowFX (FXTest.FXTestCase): Not supported if ShaderUsage == MINIMAL
  testWordsShadowFX (FXTest.FXTestCase): Not supported if ShaderUsage == MINIMAL
  testFXUpdate (FXTest.FXTestCase): Not supported if ShaderUsage == MINIMAL
  testChromaKeyFX (FXTest.FXTestCase): Not supported if ShaderUsage == MINIMAL
  testHinting (WordsTest.WordsTestCase): Linux support requires modified font config
  testVideoWriter (AVTest.AVTestCase): VideoWriter not supported under GLES.
  testStateMachineDiagram (PythonTest.PythonTestCase): graphviz not installed.
# FAIL: Test.py

1 of 1 test failed
# Please report to uzadow@libavg.de

**Comment by uzadow** [comment]
Thanks. These appear to be minor differences in rendering, so actually this report is good news :-).

Still, it would be great if you could attach the generated test images to the report: zip up the contents of src/test/resultimages, upload them somewhere and post the link.

Just curious: How long does the compile take?

**Comment by sissou92** [comment]
Hello,
Report is available in:
http://www.mediafire.com/download/md6myg2rp9xpuh3/resultimages-libavg-1.8.1_raspberrypi2-3.18.7-v7.tar.gz
Compilation take less than 1 hour ...
The performance playing Video are really not good : Video Freeze and the sound are not decoded ("noise").
The same video (mp4) is working well with "omxplayer".
Do you have any idea ?
Thanks in advance

**Comment by sissou92** [comment]
Hello,
I understand that the difference between playing the Video with AVG vs OMXPLAYER is the : Hardware video acceleration: OpenMAX.
  
I am trying to use the OpenMAX hardware on Raspberry Pi 2... 

I started to use the following version:
https://github.com/hellbender3069/libavg_OpenMax_New/commits/experiments/libavg_pi_openmax
but the test is failed...

Can you help/advice ?

Thanks in advance.

========================== TEST RESULT ========================
check in plugin
make[1]: Entering directory '/home/pi/rpi2-install/xibo/libavg/src/test/plugin'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/pi/rpi2-install/xibo/libavg/src/test/plugin'
make[1]: Entering directory '/home/pi/rpi2-install/xibo/libavg/src/test'
make  check-TESTS
make[2]: Entering directory '/home/pi/rpi2-install/xibo/libavg/src/test'
Wiping out directory: /home/pi/rpi2-install/xibo/libavg/src/test/libavg
[15-04-08 16:27:27.051][INFO][......APP] : Using libavg from: /home/pi/rpi2-install/xibo/libavg/src/test/libavg
[15-04-08 16:27:27.306][INFO][...CONFIG] : Display bpp: 24
[15-04-08 16:27:27.307][INFO][...CONFIG] : Requested OpenGL configuration: 
[15-04-08 16:27:27.307][INFO][...CONFIG] :   OpenGL flavor: Mobile (ES)
[15-04-08 16:27:27.308][INFO][...CONFIG] :   Pixel buffers: true
[15-04-08 16:27:27.308][INFO][...CONFIG] :   Power of 2 textures: false
[15-04-08 16:27:27.309][INFO][...CONFIG] :   No multisampling
[15-04-08 16:27:27.309][INFO][...CONFIG] :   Shader usage: auto
[15-04-08 16:27:27.310][INFO][...CONFIG] :   Debug context: true
[15-04-08 16:27:27.388][INFO][...CONFIG] : Loading shaders from /home/pi/rpi2-install/xibo/libavg/src/test/libavg/shaders
[15-04-08 16:27:27.390][INFO][...CONFIG] : OpenGL configuration: 
[15-04-08 16:27:27.390][INFO][...CONFIG] :   OpenGL version: OpenGL ES 2.0
[15-04-08 16:27:27.391][INFO][...CONFIG] :   OpenGL vendor: Broadcom
[15-04-08 16:27:27.391][INFO][...CONFIG] :   OpenGL renderer: VideoCore IV HW
[15-04-08 16:27:27.392][INFO][...CONFIG] :   OpenGL flavor: Mobile (ES)
[15-04-08 16:27:27.393][INFO][...CONFIG] :   Pixel buffers: true
[15-04-08 16:27:27.393][INFO][...CONFIG] :   Power of 2 textures: false
[15-04-08 16:27:27.393][INFO][...CONFIG] :   No multisampling
[15-04-08 16:27:27.394][INFO][...CONFIG] :   Shader usage: minimal
[15-04-08 16:27:27.394][INFO][...CONFIG] :   Debug context: false
[15-04-08 16:27:27.395][INFO][...CONFIG] :   Not using GL memory extensions
[15-04-08 16:27:27.395][INFO][...CONFIG] :   Max. texture size: 2048
[15-04-08 16:27:27.396][INFO][...CONFIG] :   GPU-based YUV-RGB conversion: yes.
[15-04-08 16:27:27.397][.ERR][...CONFIG] :   Dedicated video memory: Unknown
[15-04-08 16:27:27.397][.ERR][...CONFIG] :   Video memory used at start: Unknown
[15-04-08 16:27:27.400][WARN][.....NONE] : Could not get valid refresh rate
[15-04-08 16:27:27.401][WARN][.....NONE] : Defaulting to 60 Hz refresh rate.
[15-04-08 16:27:27.401][INFO][...CONFIG] : Vertical Refresh Rate: 60
[15-04-08 16:27:27.402][INFO][...CONFIG] : Hardware video acceleration: OpenMAX
[15-04-08 16:27:27.402][INFO][...CONFIG] : Pixels per mm: 3.77953
[15-04-08 16:27:27.549][WARN][...CONFIG] : Can't open audio: Audio device is already opened
Skipping multi-window tests - only supported under Linux w/GLXtestColorNodePlugin (PluginTest.PluginTestCase) ... ok
testPoint (PlayerTest.PlayerTestCase) ... ok
testBasics (PlayerTest.PlayerTestCase) ... ok
testSetResolution (PlayerTest.PlayerTestCase) ... ok
testColorParse (PlayerTest.PlayerTestCase) ... ok
testFakeTime (PlayerTest.PlayerTestCase) ... ok
testDivResize (PlayerTest.PlayerTestCase) ... ok
testRotate (PlayerTest.PlayerTestCase) ... ok
testRotate2 (PlayerTest.PlayerTestCase) ... ok
testRotatePivot (PlayerTest.PlayerTestCase) ... ok
testOpacity (PlayerTest.PlayerTestCase) ... ok
testOutlines (PlayerTest.PlayerTestCase) ... ok
testWordsOutlines (PlayerTest.PlayerTestCase) ... ok
testError (PlayerTest.PlayerTestCase) ... ok
testExceptionInTimeout (PlayerTest.PlayerTestCase) ... ok
testInvalidImageFilename (PlayerTest.PlayerTestCase) ... ok
testInvalidVideoFilename (PlayerTest.PlayerTestCase) ... python: /usr/include/boost/smart_ptr/shared_ptr.hpp:424: T* boost::shared_ptr<T>::operator->() const [with T = avg::MCTexture]: Assertion `px != 0' failed.
/bin/bash: line 5:   896 Aborted                 ${dir}$tst
FAIL: Test.py
=================================
1 of 1 test failed
Please report to uzadow@libavg.de
=================================
Makefile:563: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 1
make[2]: Leaving directory '/home/pi/rpi2-install/xibo/libavg/src/test'
Makefile:711: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/pi/rpi2-install/xibo/libavg/src/test'
Makefile:434: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

**Comment by uzadow** [comment]
You're right that there is no hardware video acceleration for the Pi in current libavg. The experiments/libavg_pi_openmax branch was never completed by the author - I don't think it works.

**Comment by sissou92** [comment]
How we can progress on this point. I am ready to contribute :-)
The test failed is "testInvalidVideoFilename". Do you know Can I fix it ?

**Comment by uzadow** [comment]
Good to see someone wanting to help!

The branch is not my code, but my hunch is that it never got to the point where any video decoding worked, so . On the other hand, I will probably get to working on this myself in the next months (no promises, though!), and it would be good to have some help.
What I'm doing right now is fixing some other crashes that happen on the Pi (See #631), and what would be really cool if you could try to reproduce them. If you install 1.8.1, they don't happen, right? What happens with current git on your Pi? Do you have a Pi B+ (the old 1-core model) that you could use to see if it happens there?

**Comment by sissou92** [comment]
It seems that the issue #631 will happen when the resolution is set the 1080p (1920x1080). In this case, you have to:
Run sudo raspi-config
Choose 8 Advanced Options
Choose A3 Memory Split
Change the value from 64 to 128 or 256

I will continue to "debug" this branch... can you just tell me how Can I have more traces ? activate the AVG_TRACE traces ?
Thanks in advance.

**Comment by uzadow** [comment]
If you want to continue working on this, maybe talk to @klemmster or @hellbender3069 and see what they suggest.

**Comment by sissou92** [comment]
ok, I will talk to him. 
In the mid-time, can you tell me how the AVG_TRACE traces can be enabled ?
Thanks.

**Comment by uzadow** [comment]
$ export AVG_LOG_CATEGORIES="CONFIG:INFO APP:DBG PROFILE:DBG MEMORY"
or similar.

**Comment by hellbender3069** [comment]
RPi2 fails test of player 

Running suite PlayerTestSuite
  Running PlayerTest
Creating window failed: GLX is not supported. (size=[      160,      120], bpp=24).
######## PlayerTestSuite failed. ########
FAIL: testplayer
=================================
1 of 1 test failed
Please report to uzadow@libavg.de
=================================

Seems it doesn't use EGL but GLX instead.

**Comment by uzadow** [comment]
@hellbender3069, I'm moving your issue to a new bugreport (Bug #723) - this bug is messy enough as it is.

**Comment by scotty007** [comment]
Outdated. Rasperry Pi specific build configuration and render code has been removed, support was added to Mesa and SDL2. Building on Raspberry Pi OS just requires `cmake -DAVG_ENABLE_EGL=TRUE` now.
