### ISSUE TITLE
Win: Logger test exits with error

### ISSUE THREAD

**Issue by uzadow** [libavg/libavg#630]
Running Test.py logger results in:
```
[15-03-30 18:18:39.912][INFO][......APP] : Using libavg from: C:\Python27\lib\site-packages\libavg
[15-03-30 18:18:39.953][INFO][...CONFIG] : Display bpp: 24
[15-03-30 18:18:39.956][INFO][...CONFIG] : Requested OpenGL configuration:
[15-03-30 18:18:39.958][INFO][...CONFIG] :   OpenGL flavor: Desktop
[15-03-30 18:18:39.960][INFO][...CONFIG] :   Pixel buffers: true
[15-03-30 18:18:39.963][INFO][...CONFIG] :   Power of 2 textures: false
[15-03-30 18:18:39.966][INFO][...CONFIG] :   No multisampling
[15-03-30 18:18:39.968][INFO][...CONFIG] :   Shader usage: auto
[15-03-30 18:18:39.970][INFO][...CONFIG] :   Debug context: true
[15-03-30 18:18:40.609][INFO][...CONFIG] : Loading shaders from C:\Python27\lib\site-packages\libavg\shaders
[15-03-30 18:18:40.614][INFO][...CONFIG] : OpenGL configuration:
[15-03-30 18:18:40.615][INFO][...CONFIG] :   OpenGL version: 4.4.0
[15-03-30 18:18:40.617][INFO][...CONFIG] :   OpenGL vendor: NVIDIA Corporation
[15-03-30 18:18:40.620][INFO][...CONFIG] :   OpenGL renderer: GeForce GTX 750/PCIe/SSE2
[15-03-30 18:18:40.622][INFO][...CONFIG] :   OpenGL flavor: Desktop
[15-03-30 18:18:40.624][INFO][...CONFIG] :   Pixel buffers: true
[15-03-30 18:18:40.626][INFO][...CONFIG] :   Power of 2 textures: false
[15-03-30 18:18:40.628][INFO][...CONFIG] :   No multisampling
[15-03-30 18:18:40.630][INFO][...CONFIG] :   Shader usage: full
[15-03-30 18:18:40.632][INFO][...CONFIG] :   Debug context: false
[15-03-30 18:18:40.634][INFO][...CONFIG] :   Using pixel buffer objects
[15-03-30 18:18:40.636][INFO][...CONFIG] :   Max. texture size: 16384
[15-03-30 18:18:40.638][INFO][...CONFIG] :   GPU-based YUV-RGB conversion: yes.
[15-03-30 18:18:40.640][INFO][...CONFIG] :   Dedicated video memory: 2048 MB
[15-03-30 18:18:40.642][INFO][...CONFIG] :   Video memory used at start: 321 MB
[15-03-30 18:18:40.645][INFO][...CONFIG] : Vertical Refresh Rate: 60
[15-03-30 18:18:40.647][INFO][...CONFIG] : Hardware video acceleration: Off
[15-03-30 18:18:40.649][INFO][...CONFIG] : Pixels per mm: 3.77953
[15-03-30 18:18:40.689][INFO][...CONFIG] : Image cache size: CPU=4083MB, GPU=16MB

testRemoveSink (LoggerTest.LoggerTestCase) ... ok
testConfigureCategory (LoggerTest.LoggerTestCase) ... ok
testReconfigureCategory (LoggerTest.LoggerTestCase) ... ok
testOmitCategory (LoggerTest.LoggerTestCase) ... ok
testLogCategory (LoggerTest.LoggerTestCase) ... ok
testUnknownCategoryWarning (LoggerTest.LoggerTestCase) ... ok

----------------------------------------------------------------------
Ran 6 tests in 0.004s

OK
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\lib\logging\__init__.py", line 1615, in shutdown
    h.flush()
  File "C:\Python27\lib\logging\__init__.py", line 824, in flush
    self.stream.flush()
  File "C:\Python27\lib\StringIO.py", line 256, in flush
    _complain_ifclosed(self.closed)
  File "C:\Python27\lib\StringIO.py", line 40, in _complain_ifclosed
    raise ValueError, "I/O operation on closed file"
ValueError: I/O operation on closed file
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Python27\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Python27\lib\logging\__init__.py", line 1615, in shutdown
    h.flush()
  File "C:\Python27\lib\logging\__init__.py", line 824, in flush
    self.stream.flush()
  File "C:\Python27\lib\StringIO.py", line 256, in flush
    _complain_ifclosed(self.closed)
  File "C:\Python27\lib\StringIO.py", line 40, in _complain_ifclosed
    raise ValueError, "I/O operation on closed file"
ValueError: I/O operation on closed file
```

**Comment by uzadow** [comment]
Fix (in LoggerTestCase):
```
    def tearDown(self):
        self.pyLogger.removeHandler(self.hdlr)
        logger.removeSink(self.pyLogger)
        self.stream = None
        self.hdlr = None
```
