### ISSUE TITLE
Test failure with boost 1.60

### ISSUE THREAD

**Issue by uzadow** [libavg/libavg#728]
libavg compiled using gcc 5.2 and boost 1.60 generates the following exception when importing libavg:
```
Traceback (most recent call last):
  File "./Test.py", line 97, in <module>
    import libavg
  File "/Users/uzadow/devel/libavg/libavg/src/test/libavg/__init__.py", line 13, in <module>
    from avg import *
TypeError: No registered converter was able to produce a C++ rvalue of type std::string from this Python object of type str
```

**Comment by uzadow** [comment]
Fixing in the  bugfix/boost_1_60 branch
