### ISSUE TITLE
avg_checkcamera.py crashes when pixelformat is not given.

### ISSUE THREAD

**Issue by uzadow** [libavg/libavg#740]
Configuration: Linux, Video4Linux camera that delivers jpegs.

Result with pixformat is that the image is shown as expected:
```
$ avg_showcamera.py --driver=video4linux --pixformat=JPEG
```
Without pixformat:
```
$ avg_showcamera.py --driver=video4linux
Segmentation fault (core dumped)
```
Stacktrace:
```
#0  avg::createTrueColorCopy<avg::Pixel32, avg::Pixel24> (destBmp=..., srcBmp=...) at Pixel24.h:159
#1  0x00007ffff56adda1 in avg::createTrueColorCopy<avg::Pixel32> (destBmp=..., srcBmp=...) at Bitmap.cpp:1810
#2  0x00007ffff56acf15 in avg::Bitmap::copyPixels (this=0x1081280, origBmp=...) at Bitmap.cpp:281
#3  0x00007ffff57092f7 in avg::Camera::convertCamFrameToDestPF (this=this@entry=0x1082750, pCamBmp=...) at Camera.cpp:85
#4  0x00007ffff571045a in avg::V4LCamera::getImage (this=0x1082750, bWait=<optimized out>) at V4LCamera.cpp:233
#5  0x00007ffff5644529 in avg::CameraNode::updateToLatestCameraImage (this=this@entry=0x10823f0) at CameraNode.cpp:388
#6  0x00007ffff5646ba5 in avg::CameraNode::preRender (this=this@entry=0x10823f0, pVA=..., 
    bIsParentActive=bIsParentActive@entry=true, parentEffectiveOpacity=<optimized out>) at CameraNode.cpp:343
[...]
```

It seems that the camera is created expecting an RGB image by default, and if that isn't supported, it crashes.

**Comment by uzadow** [comment]
Fixed in e0c45b2007c3f7b53c6072d153814ee5df9b5cb8
